#!/bin/sh
# help usage                        ./do h 
# Development-Start gcad3d          ./do


# if test -f WinIsLast.lock; then
#   rm -rf WinIsLast.lock
#   cp -f dirx.lst ~/gCAD3D/cfg/dir.lst
#   cp -f dirw.lst ~/gCAD3D/cfg/dir.lst
# fi

# get bitNr BINLOC gcad_dir_bin DirBasSer
. ../options.sh


cmdVi=${DIR_BIN}'vi.sh'
#cmdVi='vim -N -u /mnt/serv1/Linux/bin/.vimrc'
#echo $cmdVi



if test "$1" = "help"; then
  echo "./do complete          # do all following"
  echo "./do delete            # delete all objects"
  echo "./do guiinit           # change gui-version"
  echo "./do gui               # rebuild xa_gui_gtk-*.so"
  echo "./do c                 # compile & link core"
  echo "./do all               # compile & link corelibs"
  echo "./do allDemos          # compile & link demos"
  echo "./do cp2serv1          # copy -> server before build"
  echo "./do                   # start"
  echo "./do d                 # start with debugger"
  echo "./do trc               # start with mtrace"
  echo "./do ud                # display userDoc"
  echo "./do dd                # display devDoc"
  echo "./do udd               # update & display devDoc"
  echo "./do gty               # display AP_types.h"
  echo "./do gh                # display ut_geo.h"
  echo "./do g2                # display ut_geo3d.c"
  echo "./do g3                # display ut_geo3d.c"
  echo "./do gmon              # analyze time"
  exit 0
fi



if test "$1" = "complete"; then
  ./del_obj.sh
# create xa_gui_(VGUI).so
  make -f gcad_gui__.mak
# create link xa_gui.so <- xa_gui_(VGUI).so
  make -f gcad_gui__.mak link
# create core
  make -f gcad3d.mak
# create core-dll's
  make -f gcad3d.mak all
# create demo-plugins
  make -f gcad3d.mak allDemos
  exit 0
fi


if test "$1" = "delete"; then
  ./del_obj.sh
  exit 0
fi


if test "$1" = "guiinit"; then
  vi ../options.mak
  make -f gcad_gui__.mak delete
  make -f gcad_gui__.mak
  make -f gcad_gui__.mak link
  exit 0
fi


if test "$1" = "gui"; then
  make -f gcad_gui__.mak
  make -f gcad_gui__.mak link
  exit 0
fi


if test "$1" = "cp2serv1"; then
  cp -f ${gcad_dir_bin}/gCAD3D ${DirBinSer}/.
  cp  -f ${gcad_dir_bin}/*.so ${DirBinSer}/.
  cp -rf ${gcad_dir_bin}/plugins ${DirBinSer}/.
  exit 0
fi


if test "$1" = "c"; then
  make -f gcad3d.mak
  exit 0
fi

if test "$1" = "all"; then
  make -f gcad3d.mak all
  exit 0
fi

if test "$1" = "allDemos"; then
  make -f gcad3d.mak allDemos
  exit 0
fi

if test "$1" = "guiinit"; then
  ./gui_init.sh
  exit 0
fi

if test "$1" = "gui"; then
  make -f xa_gui_gtk.mak
  make link -f gui_util.mak
  exit 0
fi

if test "$1" = "ud"; then
  firefox ../../doc/html/index_de.htm 2>/dev/null &
  exit 0
fi

if test "$1" = "dd"; then
  firefox ../../doc/gcad/index.htm
  exit 0
fi

if test "$1" = "udd"; then
  cd /mnt/serv1/Devel/GITHUB/gcad3d/doc && ./gcad_doxygen.sh > t1
  exit 0
fi

if test "$1" = "gty"; then
  $cmdVi ../ut/AP_types.h
  exit 0
fi

if test "$1" = "gh"; then
  $cmdVi ../ut/ut_geo.h
  exit 0
fi

if test "$1" = "g2"; then
  $cmdVi ../ut/ut_geo2d.c
  exit 0
fi

if test "$1" = "g3"; then
  $cmdVi ../ut/ut_geo3d.c
  exit 0
fi





#=================================================================
# start gCAD3D

#export UBUNTU_MENUPROXY=

OSTYPE=`uname`
# "Linux" = Ubuntu 12/32
echo "start - OSTYPE = " $OSTYPE


if [ "$OSTYPE" = "Linux" ] ; then

# executables (shared-libs ..)
# export gcad_dir_bin=${DirBasSer}/gCAD3D/binLinux${bitNr}/
# export gcad_dir_bin=${DirBasSer}/binLinux${bitNr}/
  export gcad_dir_bin=${gcad_dir_bin}/
  export LD_LIBRARY_PATH=${gcad_dir_bin}

# icons,
  export gcad_dir_ico=${DirBasSer}/icons/

# def is /usr/share/gcad3d/
  export gcad_dir_local=${DirBasSer}/

# html and msg-files
# def is /usr/share/doc/
  export gcad_dir_doc=${DirBasSer}/doc/



  exeNam=${gcad_dir_bin}gCAD3D



#-----------------------------------------------------
# analyze times in file gmon.out - AFTER run gcad
if [ "$1" = "gmon" ] ; then
  gprof ${exeNam} > t1 && vi t1
  exit 0



#-----------------------------------------------------
# d = debug
elif [ "$1" = "d" ] ; then
  gdb ${exeNam} $* -x gCAD3D.gdb
  #nemiver ${gcad_dir_bin}/gCAD3D
  exit 0


#-----------------------------------------------------
# trc ?
elif [ "$1" = "trc" ] ; then
  export MALLOC_TRACE=mtrace.txt
  ${exeNam}
  #mtrace  ${exeNam} $MALLOC_TRACE
  exit 0


#-----------------------------------------------------
# init = copy dirx.lst -> ?
elif [ "$1" = "init" ] ; then
	echo "copy dir.lst"
  cp -f ../../gCAD3D/cfg/dir.lst ~/gCAD3D/cfg/dir.lst
  exit 0

#-----------------------------------------------------
fi

echo "normal start .."
# i = Init (nach MS_Windows)
#if test "$1" = "i"; then
#fi
  
#./gCAD3D.sh $*
${exeNam} $*
exit



#----------------------------------------------------
elif [ "$OSTYPE" = "msys" ] ; then
  cp -f dirw.lst dir.lst
  #cp -f xa.rc_MS ../tmp\xa.rc
  cd ..
  gdb binMS32/gCAD3D.exe $*


#-----------------------------------------------------
else
  echo "OPSYS $OSTYPE not supported .."
  exit -1
fi


# EOF
