#! /bin/sh

# script for cscope


# set EDITOR = name of script-file with editor-call
# echo "vim -N -u ~/.vimrc $*" > ~/vim.sh
#EDITOR=~/vim/vi
EDITOR=${DIR_BIN}'vi.sh'
export EDITOR


# get OS (eg "Linux32")
bitNr=`getconf LONG_BIT`
OS=Linux${bitNr}
#echo ${OS}


# get bitNr BINLOC gcad_dir_bin DirBasSer
. ../options.sh

# create list of gcad-sourcefiles in file srcFiles
make -f gcad3d.mak srclst > /dev/null
# add gui-sources
make -f gcad_gui__.mak add_srclst
#cat srcFiles

# start
cscope -i srcFiles

exit
#
