#! /bin/sh
#
# Startproc for gCAD3D.
# You can modify several directories; default is ${HOME}/gCAD3D/..

#osVer=`getconf LONG_BIT`
# 32|64
#osVer=${HOSTTYPE}
hTyp=`uname -s`_`uname -i`

#export LD_LIBRARY_PATH=`dirname $0`

# <gcad_dir_bin>                   executable, dll's     ReadOnly
# <gcad_dir_bin>plugins/           dll's                 ReadOnly
#export gcad_dir_bin=/usr/lib/gCAD3D/binLinux${osVer}/
export gcad_dir_bin=/usr/lib/gcad3d/${hTyp}/

# <gcad_dir_bas>examples.gz        local-setup           RO
# <gcad_dir_bas>icons/             icons                 RO
#export gcad_dir_bas=/usr/share/gcad3d/

# <gcad_dir_doc>html/              helpfiles .htm        ReadOnly
# <gcad_dir_doc>msg/               helpfiles .txt        ReadOnly
#export gcad_dir_doc=/usr/share/doc/gcad3d/

# <gcad_dir_local>gCAD3D/tmp/      temp-files            ReadWrite
# <gcad_dir_local>gCAD3D/cfg/      local setup-files     ReadWrite
# <gcad_dir_local>gCAD3D/dat/      example-models        ReadWrite
# <gcad_dir_local>gCAD3D/prg/      script-parts          ReadWrite
# <gcad_dir_local>gCAD3D/ctlg/     catalog-parts         ReadWrite
#export gcad_dir_local=${HOME}/

# <gcad_dir_dev>gCAD3D/dev/        sources plugins       ReadWrite
# <gcad_dir_dev>gCAD3D/plugins/    objects executables   ReadWriteExe
#export gcad_dir_dev=${HOME}/


## if menu is unvisible: (ubuntu 11):
#if [ -n "$UBUNTU_MENUPROXY" ]; then
#  echo "disactivate ubuntu-global-menu"
#  export UBUNTU_MENUPROXY=
#fi

# start it ..
#dirname $0`/gCAD3Dx32
export LD_LIBRARY_PATH=${gcad_dir_bin}
${gcad_dir_bin}/gCAD3D $*
# eof
