#! /bin/sh
#
# Startproc for gCAD3D.
# You can modify several directories; default is ${HOME}/gCAD3D/..

#osVer=`getconf LONG_BIT`
# 32|64
#osVer=${HOSTTYPE}
hTyp=`uname -s`_`uname -m`
echo ${PWD}/gcad3d ${hTyp}

# <gcad_dir_bin>                     executable, dll's     ReadOnly
# <gcad_dir_bin>plugins/             dll's                 ReadOnly
#export gcad_dir_bin=/usr/lib/gCAD3D/binLinux${osVer}/
export gcad_dir_bin=/usr/lib/gcad3d/${hTyp}/

# <gcad_dir_bas>examples.gz          local-setup           RO
# <gcad_dir_bas>icons/               icons                 RO
#export gcad_dir_bas=/usr/share/gcad3d/

# <gcad_dir_doc>html/                helpfiles .htm        ReadOnly
# <gcad_dir_doc>msg/                 helpfiles .txt        ReadOnly
export gcad_dir_doc=/usr/share/doc/gcad3d/

# <gcad_dir_local>gCAD3D/            application-files     ReadWrite
# <gcad_dir_local>gCAD3D/tmp/        temp-files            ReadWrite
# <gcad_dir_local>gCAD3D/cfg_Linux/  local setup-files     ReadWrite
# <gcad_dir_local>gCAD3D/dat/        example-models        ReadWrite
# <gcad_dir_local>gCAD3D/prg/        script-parts          ReadWrite
# <gcad_dir_local>gCAD3D/ctlg/       catalog-parts         ReadWrite
#export gcad_dir_local=${HOME}/

# <gcad_dir_dev>gCAD3D/dev/          sources plugins       ReadWrite
# <gcad_dir_dev>gCAD3D/plugins/      objects executables   ReadWriteExe
#export gcad_dir_dev=${HOME}/


export LD_LIBRARY_PATH=${gcad_dir_bin}


# start in debug-mode
if [ "$1" = "gdb" ]; then
# file ${gcad_dir_bin}gCAD3D
# ldd ${gcad_dir_bin}/gCAD3D
  shift
  gdb ${gcad_dir_bin}/gCAD3D $*
  exit
fi


# start it ..
echo "starting " ${gcad_dir_bin}gCAD3D $*
${gcad_dir_bin}gCAD3D $*
# eof
